global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#yaroslav_kalinkin'
