version: '3.3'

services:
  source:
    image: ${USERNAME}/source
    volumes:
      - source_app:/reddit/app
  post_db:
    image: mongo:3.2
    volumes:
     - post_db:/data/db
    networks:
      back_net:
        aliases:
         - post_db
         - comment_db
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_VERSION}
    volumes:
      - source_app:/reddit/app
    ports:
     - ${PUBLIC_PORT}:${PUBLIC_PORT}/tcp
    networks:
     - front_net
    depends_on:
      - source
  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST_VERSION}
    volumes:
      - source_app:/reddit/app
    networks:
      front_net:
        aliases:
         - post
      back_net:
    depends_on:
      - source
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    volumes:
      - source_app:/reddit/app
    command: "puma --debug -w 2"
    networks:
      front_net:
        aliases:
         - comment
      back_net:
    depends_on:
      - source

volumes:
  post_db:
  source_app:

networks:
  back_net:
    ipam:
      config:
      -
        subnet: 10.0.2.0/24
  front_net:
    ipam:
      config:
      -
        subnet: 10.0.1.0/24

